name: rally-cap
version: '${project.version}'
main: org.oreo.rallycap.Rally_cap
api-version: '1.20'


commands:
  rally-cap:
    description: Cap a nations rally
    usage: /<command>
    aliases: [ rallyCap ]